# Generated by Django 5.2.16 on 2026-08-19 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_class_sort_order'),
        ('attendance', '0003_alter_attendancerecord_status_attendanceauditlog'),
        ('schools', '0011_remove_legacy_logo_file'),
        ('sis', '0011_alter_student_section_record'),
        ('staff', '0011_one_teacher_per_section_subject'),
        ('timetable', '0002_alter_timetableslot_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'period', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_student_attendance_date',
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='period',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='period',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attendance_records', to='staff.teacher'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='time_label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='timetable.timetableslot'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'date'], name='attendance_student_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'date', 'period'], name='att_school_date_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'date', 'period'), name='unique_student_date_period'),
        ),
    ]
