# Generated by Django 5.2.16 on 2026-08-19 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_class_sort_order'),
        ('attendance', '0004_alter_attendancerecord_options_and_more'),
        ('schools', '0011_remove_legacy_logo_file'),
        ('sis', '0011_alter_student_section_record'),
        ('staff', '0011_one_teacher_per_section_subject'),
        ('timetable', '0002_alter_timetableslot_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceauditlog',
            name='day_of_week',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='day_of_week',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'day_of_week'], name='att_school_day_idx'),
        ),
    ]
