# Generated by Django 5.2.16 on 2026-08-18 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_fcm_device_registry'),
        ('schools', '0011_remove_legacy_logo_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='broadcast_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['broadcast_id'], name='notificatio_broadca_b03624_idx'),
        ),
    ]
