# Generated by Django 5.2.17 on 2026-08-27 09:24

import apps.community.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0011_remove_legacy_logo_file'),
        ('sis', '0011_alter_student_section_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('School event', 'School event'), ('Workshop', 'Workshop'), ('Competition', 'Competition'), ('Seminar', 'Seminar'), ('Sports', 'Sports'), ('Cultural', 'Cultural')], default='School event', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(blank=True, help_text='Event end date and time', null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Deadline date and time after which registrations are closed', null=True)),
                ('venue', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('ticket_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Published', max_length=20)),
                ('audience', models.CharField(default='Teachers, students and parents', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schools.school')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(max_length=160)),
                ('attendee_email', models.EmailField(blank=True, max_length=254)),
                ('attendee_phone', models.CharField(blank=True, max_length=30)),
                ('class_name', models.CharField(blank=True, max_length=40)),
                ('section', models.CharField(blank=True, max_length=40)),
                ('roll_no', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ticket_code', models.CharField(default=apps.community.models.generate_ticket_code, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Attended', 'Attended'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='sis.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='community.schoolevent')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Announcement', 'Announcement'), ('Awareness campaign', 'Awareness campaign'), ('School achievement', 'School achievement'), ('Social update', 'Social update')], default='Announcement', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(default='Teachers, students and parents', max_length=100)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('author_name', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'created_at'], name='community_c_school__30769e_idx'), models.Index(fields=['school', 'kind'], name='community_c_school__694d6c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='schoolevent',
            index=models.Index(fields=['school', 'date'], name='community_s_school__dd6550_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolevent',
            index=models.Index(fields=['school', 'status'], name='community_s_school__469076_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolevent',
            index=models.Index(fields=['school', 'registration_deadline'], name='community_s_school__b0f3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['school', 'event'], name='community_e_school__6c7aae_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['ticket_code'], name='community_e_ticket__637d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['school', 'user'], name='community_e_school__67df51_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['school', 'student'], name='community_e_school__acb889_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Confirmed'), ('student__isnull', False)), fields=('event', 'student'), name='unique_event_student_active_reg'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Confirmed'), ('user__isnull', False)), fields=('event', 'user'), name='unique_event_user_active_reg'),
        ),
    ]
