# Generated by Django 5.2.16 on 2026-07-17 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('assigned_sections', models.JSONField(blank=True, default=list)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('joining_date', models.DateField()),
                ('phone', models.CharField(max_length=30)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'status'], name='staff_teach_school__1d3f75_idx'), models.Index(fields=['school', 'phone'], name='staff_teach_school__71433b_idx')],
            },
        ),
    ]
