# Generated by Django 5.2.16 on 2026-08-06 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_class_sort_order'),
        ('schools', '0011_remove_legacy_logo_file'),
        ('staff', '0009_teacher_subject_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teacher_teaching_assignments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_teaching_assignments', to='schools.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='staff.teacher')),
            ],
            options={
                'ordering': ['section_id', 'subject_id', 'id'],
                'indexes': [models.Index(fields=['school', 'teacher'], name='staff_assignment_teacher_idx'), models.Index(fields=['school', 'section', 'subject'], name='staff_assignment_scope_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'teacher', 'section', 'subject'), name='unique_teacher_section_subject_assignment')],
            },
        ),
    ]
