# Generated by Django 5.2.16 on 2026-07-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=160)),
                ('class_name', models.CharField(max_length=40)),
                ('section', models.CharField(max_length=10)),
                ('roll_no', models.PositiveIntegerField()),
                ('parent_name', models.CharField(max_length=160)),
                ('parent_phone', models.CharField(max_length=30)),
                ('parent_email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=32)),
                ('address', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Promoted', 'Promoted'), ('TC_Issued', 'Tc Issued')], default='Active', max_length=16)),
                ('academic_year', models.CharField(max_length=10)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fee_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fee_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=40)),
                ('section', models.CharField(max_length=10)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(max_length=32)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sis.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='student-documents/')),
                ('status', models.CharField(default='Pending', max_length=16)),
                ('file_type', models.CharField(max_length=12)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sis.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_name', 'section'], name='sis_student_school__1f8361_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'academic_year'], name='sis_student_school__bffbda_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'admission_no', 'academic_year'), name='unique_admission_year'),
        ),
    ]
