# Generated by Django 5.2.16 on 2026-08-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_class_sort_order'),
        ('sis', '0010_alter_student_academic_year_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.section'),
        ),
    ]
