# Generated by Django 5.2.16 on 2026-08-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_class_sort_order'),
        ('staff', '0011_one_teacher_per_section_subject'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.section'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='staff.teacher'),
        ),
    ]
