import { useState } from 'react';
import { Link, useLocation } from 'react-router';
import { ArrowRight, Building2, Menu, X } from 'lucide-react';

const links = [{ label: 'Platform', to: '/platform' }, { label: 'How it works', to: '/how-it-works' }, { label: 'For your school', to: '/roles' }, { label: 'Security', to: '/security' }, { label: 'Contact', to: '/contact' }];

export default function MarketingNavbar() {
  const [open, setOpen] = useState(false);
  const { pathname } = useLocation();
  return <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8"><Link to="/" className="flex items-center gap-3" aria-label="Volpehub Education home"><span className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-indigo-600 via-indigo-600 to-violet-500 shadow-lg shadow-indigo-200"><Building2 className="h-5 w-5 text-white" /></span><span><span className="block text-sm font-extrabold tracking-tight text-slate-950">Volpehub Education</span><span className="block text-[10px] font-bold uppercase tracking-[.17em] text-indigo-600">School ERP platform</span></span></Link><nav className="hidden items-center rounded-2xl border border-slate-200 bg-slate-50/80 p-1 text-sm font-bold text-slate-600 lg:flex" aria-label="Primary navigation">{links.map(({ label, to }) => <Link key={to} to={to} className={`rounded-xl px-3 py-2 transition ${pathname === to ? 'bg-white text-indigo-700 shadow-sm' : 'hover:text-indigo-600'}`}>{label}</Link>)}</nav><div className="hidden items-center gap-2 lg:flex"><Link to="/login" className="rounded-xl px-3 py-2 text-sm font-bold text-slate-700 transition hover:bg-slate-100">Sign in</Link><Link to="/demo" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-slate-300 transition hover:-translate-y-0.5 hover:bg-indigo-700">Talk to us <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div><button type="button" onClick={() => setOpen((current) => !current)} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-700 lg:hidden" aria-label="Toggle navigation" aria-expanded={open}>{open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>{open && <nav className="border-t border-slate-100 bg-white px-5 py-4 shadow-lg lg:hidden" aria-label="Mobile navigation"><div className="mx-auto grid max-w-7xl gap-1">{links.map(({ label, to }) => <Link key={to} onClick={() => setOpen(false)} to={to} className={`rounded-xl px-3 py-3 text-sm font-bold ${pathname === to ? 'bg-indigo-50 text-indigo-700' : 'text-slate-700 hover:bg-slate-50'}`}>{label}</Link>)}<div className="mt-2 grid grid-cols-2 gap-2"><Link onClick={() => setOpen(false)} to="/login" className="rounded-xl border border-slate-200 px-3 py-3 text-center text-sm font-bold text-slate-700">Sign in</Link><Link onClick={() => setOpen(false)} to="/demo" className="rounded-xl bg-slate-950 px-3 py-3 text-center text-sm font-bold text-white">Talk to us</Link></div></div></nav>}</header>;
}
