# Generated by Django 5.2.16 on 2026-08-20 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0011_remove_legacy_logo_file'),
        ('sis', '0011_alter_student_section_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(default='2026-2027', max_length=50)),
                ('level', models.CharField(choices=[('school', 'School'), ('class', 'Class'), ('section', 'Section'), ('student', 'Student')], default='class', max_length=50)),
                ('target_class', models.CharField(blank=True, max_length=50, null=True)),
                ('target_section', models.CharField(blank=True, max_length=50, null=True)),
                ('target_student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('items', models.JSONField(default=list, help_text='List of component items: [{category, amount}]')),
                ('quarters', models.JSONField(default=list, help_text='List of quarterly schedules: [{quarter, name, amount, dueDate}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_str', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=255)),
                ('admission_no', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('section_name', models.CharField(max_length=50)),
                ('academic_year', models.CharField(default='2026-2027', max_length=50)),
                ('scholarship', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hostel_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('installments_paid', models.IntegerField(default=0)),
                ('custom_items', models.JSONField(blank=True, default=list, null=True)),
                ('custom_quarters', models.JSONField(blank=True, default=list, null=True)),
                ('payment_history', models.JSONField(default=list, help_text='List of payments: [{id, paymentDate, amountPaid, paymentMethod, transactionId, receiptNo, category, installmentType}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_records', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='sis.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100)),
                ('receipt_no', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, default='School Fee Payment', max_length=100)),
                ('installment_type', models.CharField(blank=True, default='Custom', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='schools.school')),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.studentfeerecord')),
            ],
        ),
    ]
