# Generated by Django 5.2.16 on 2026-08-22 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_class_sort_order'),
        ('finance', '0002_feequarter'),
        ('sis', '0011_alter_student_section_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='academic_year_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='target_class_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='academics.class'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='target_section_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='academics.section'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='target_student_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fee_structures', to='sis.student'),
        ),
    ]
