# Generated by Django 5.2.16 on 2026-08-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_feestructure_academic_year_ref_and_more'),
        ('sis', '0011_alter_student_section_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='academic_year',
            field=models.CharField(default='2026-2027', max_length=50),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.feestructure'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='quarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.feequarter'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='sis.student'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='fee_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.studentfeerecord'),
        ),
    ]
