# Generated by Django 5.2.16 on 2026-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_refreshtokenrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refreshtokenrecord',
            new_name='accounts_re_user_id_8751ff_idx',
            old_name='accounts_re_user_id_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
